name: CI

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --diff"
          src: "tiler tests"

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # 3.6 will reach EoL in December 2021
        # https://devguide.python.org/#status-of-python-branches
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage[toml] coveralls
      - name: Run tests
        run: coverage run -m pytest -v
      - name: Submit coveralls
        if: github.repository == 'the-lay/tiler'
        run: coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
